import { Script } from "./types";

export const INITIAL_SCRIPTS: Script[] = [
  {
    id: "script-1",
    ideaId: "idea-1",
    title: "He Had ONE Job",
    description: "Sheriff has point-blank shot on the murderer, but shoots innocent Bacon Benny instead.",
    status: "IN_PRODUCTION",
    hook: "The sheriff looked into my eyes... and shot the guy eating cheese.",
    tags: ["MM2", "Funny", "SheriffFail", "RobloxShorts"],
    estimatedDuration: 42,
    createdAt: "2026-09-21T10:00:00.000Z",
    updatedAt: "2026-09-28T14:00:00.000Z",
    characters: ["char-sheriff", "char-murderer", "char-noob"],
    scenes: [
      {
        id: "scene-1-1",
        title: "Cornered in the Storage Room",
        description: "The murderer has backed Bacon Benny into the corner behind wooden crates.",
        duration: 12,
        notes: "Camera angle close-up on the Chroma knife reflection.",
        characters: ["char-murderer", "char-noob"],
        dialogue: [
          {
            id: "d-1-1",
            characterId: "char-murderer",
            emotion: "SUSPICIOUS",
            text: "Any last words before the round timer expires?",
            duration: 3.5,
          },
          {
            id: "d-1-2",
            characterId: "char-noob",
            emotion: "SCARED",
            text: "I was just looking for the cheese dispenser mister!!",
            duration: 3.0,
          },
        ],
      },
      {
        id: "scene-1-2",
        title: "The Sheriff Kicks Down the Door",
        description: "Sheriff Knox kicks open the double doors with his revolver glowing golden.",
        duration: 14,
        notes: "Dramatic action sting, slow-motion kick.",
        characters: ["char-sheriff", "char-murderer"],
        dialogue: [
          {
            id: "d-1-3",
            characterId: "char-sheriff",
            emotion: "ANGRY",
            text: "FREEZE! STEP AWAY FROM THE BACON!",
            duration: 2.5,
          },
          {
            id: "d-1-4",
            characterId: "char-murderer",
            emotion: "SURPRISED",
            text: "Wait, Knox?! How did you track my footsteps?",
            duration: 3.0,
          },
        ],
      },
      {
        id: "scene-1-3",
        title: "The Fatal Misclick",
        description: "Sheriff Knox pulls the trigger, flicking 90 degrees directly into Benny.",
        duration: 16,
        notes: "Loud gun report sound, dramatic record scratch.",
        characters: ["char-sheriff", "char-noob", "char-murderer"],
        dialogue: [
          {
            id: "d-1-5",
            characterId: "char-sheriff",
            emotion: "EXCITED",
            text: "TAKE THIS, SCUM!",
            duration: 1.5,
          },
          {
            id: "d-1-6",
            characterId: "char-noob",
            emotion: "SURPRISED",
            text: "OOF! Why me bro?!",
            duration: 2.0,
          },
          {
            id: "d-1-7",
            characterId: "char-murderer",
            emotion: "HAPPY",
            text: "Did you seriously just shoot your own witness?",
            duration: 3.5,
          },
          {
            id: "d-1-8",
            characterId: "char-sheriff",
            emotion: "CONFUSED",
            text: "My mouse sensitivity glitched, I SWEAR!",
            duration: 3.0,
          },
        ],
      },
    ],
  },
  {
    id: "script-2",
    ideaId: "idea-2",
    title: "Don't Trust The Sheriff",
    description: "An innocent player discovers the sheriff they were following is actually an imposter.",
    status: "READY",
    hook: "Always check the player list before handing over your trust...",
    tags: ["MM2", "Betrayal", "Machinima", "Story"],
    estimatedDuration: 48,
    createdAt: "2026-09-22T12:00:00.000Z",
    updatedAt: "2026-09-27T16:00:00.000Z",
    characters: ["char-detective", "char-sheriff", "char-murderer"],
    scenes: [
      {
        id: "scene-2-1",
        title: "The Safehouse Rendezvous",
        description: "Inspector Blox meets Sheriff Knox inside the library reading lounge.",
        duration: 16,
        notes: "Dim candlelight atmosphere.",
        characters: ["char-detective", "char-sheriff"],
        dialogue: [
          {
            id: "d-2-1",
            characterId: "char-detective",
            emotion: "SUSPICIOUS",
            text: "Knox, the murder happened in the basement, but your boots have attic cobwebs.",
            duration: 4.5,
          },
          {
            id: "d-2-2",
            characterId: "char-sheriff",
            emotion: "HAPPY",
            text: "Just doing routine patrol, Inspector. Nothing gets past me.",
            duration: 3.5,
          },
        ],
      },
      {
        id: "scene-2-2",
        title: "The Clue in the Mirror",
        description: "Blox spots the real Sheriff Knox tied up in the reflection of the glass mirror.",
        duration: 18,
        notes: "Creepy violin riser.",
        characters: ["char-detective", "char-murderer"],
        dialogue: [
          {
            id: "d-2-3",
            characterId: "char-detective",
            emotion: "SCARED",
            text: "Wait a second... your badge number is 404. Knox's badge is 777!",
            duration: 4.0,
          },
          {
            id: "d-2-4",
            characterId: "char-murderer",
            emotion: "HAPPY",
            text: "Took you long enough, detective. Disguise potion wearing off in 3... 2...",
            duration: 4.5,
          },
        ],
      },
      {
        id: "scene-2-3",
        title: "The Escape Sprint",
        description: "Blox flips the library table and dives out the stained-glass window.",
        duration: 14,
        notes: "Fast action obby parkour escape.",
        characters: ["char-detective"],
        dialogue: [
          {
            id: "d-2-5",
            characterId: "char-detective",
            emotion: "EXCITED",
            text: "I gotta find the real gun drop before he reaches the lobby!",
            duration: 3.5,
          },
        ],
      },
    ],
  },
  {
    id: "script-3",
    ideaId: "idea-4",
    title: "The Murderer Was AFK",
    description: "The entire server emotes around a frozen murderer until round timer hits 10 seconds.",
    status: "SCRIPTING",
    hook: "Never dance on a sleeping dragon.",
    tags: ["MM2", "Funny", "Meme", "Trolling"],
    estimatedDuration: 35,
    createdAt: "2026-09-23T14:30:00.000Z",
    updatedAt: "2026-09-28T09:00:00.000Z",
    characters: ["char-noob", "char-lucky", "char-troll", "char-murderer"],
    scenes: [
      {
        id: "scene-3-1",
        title: "The Spawn Circle Dance",
        description: "Players assemble around Slick Blade who is completely frozen standing in place.",
        duration: 15,
        notes: "Upbeat EDM dance track playing muffled.",
        characters: ["char-noob", "char-lucky", "char-troll"],
        dialogue: [
          {
            id: "d-3-1",
            characterId: "char-noob",
            emotion: "HAPPY",
            text: "Look guys, free win! He fell asleep doing homework!",
            duration: 3.0,
          },
          {
            id: "d-3-2",
            characterId: "char-troll",
            emotion: "EXCITED",
            text: "I'm stacking 5 pizza boxes on his avatar right now haha!",
            duration: 3.5,
          },
          {
            id: "d-3-3",
            characterId: "char-lucky",
            emotion: "HAPPY",
            text: "My lucky spin says this round gives 500 bonus coins!",
            duration: 3.0,
          },
        ],
      },
      {
        id: "scene-3-2",
        title: "The Jumpscare Awakening",
        description: "At 0:08 on the timer, Slick Blade's avatar head snaps 180 degrees with red eyes.",
        duration: 20,
        notes: "Heavy bass drop, red screen flash, comedic scream chorus.",
        characters: ["char-murderer", "char-noob", "char-lucky"],
        dialogue: [
          {
            id: "d-3-4",
            characterId: "char-murderer",
            emotion: "ANGRY",
            text: "Mic was on mute. Thanks for gathering into one convenient spot.",
            duration: 4.0,
          },
          {
            id: "d-3-5",
            characterId: "char-noob",
            emotion: "SCARED",
            text: "RUN FOR YOUR LIVESSSSSS!",
            duration: 2.0,
          },
        ],
      },
    ],
  },
  {
    id: "script-4",
    ideaId: "idea-3",
    title: "Never Follow The Noob",
    description: "Bacon Benny leads an entire expedition into an erupting volcano claiming it's a secret shop.",
    status: "COMPLETED",
    hook: "He said there was free Robux in the magma chamber...",
    tags: ["Comedy", "Disaster", "Noob", "Story"],
    estimatedDuration: 40,
    createdAt: "2026-09-19T08:00:00.000Z",
    updatedAt: "2026-09-26T18:00:00.000Z",
    characters: ["char-noob", "char-ninja", "char-trader"],
    scenes: [
      {
        id: "scene-4-1",
        title: "The Volcano Base Camp",
        description: "The siren blares as lava begins pouring down Mount Blox.",
        duration: 18,
        notes: "Rumbling sub-bass sound design.",
        characters: ["char-noob", "char-ninja", "char-trader"],
        dialogue: [
          {
            id: "d-4-1",
            characterId: "char-noob",
            emotion: "EXCITED",
            text: "Follow me guys! My uncle works at Roblox and built an air conditioned vault inside!",
            duration: 4.5,
          },
          {
            id: "d-4-2",
            characterId: "char-ninja",
            emotion: "SUSPICIOUS",
            text: "Benny, that is literally molten rock splashing on your shoes.",
            duration: 3.5,
          },
          {
            id: "d-4-3",
            characterId: "char-trader",
            emotion: "CONFUSED",
            text: "If there are limited items inside I am willing to risk minor third-degree burns.",
            duration: 4.0,
          },
        ],
      },
      {
        id: "scene-4-2",
        title: "The Dead End",
        description: "The tunnel terminates into a bubbling boiling lava lake with no exits.",
        duration: 22,
        notes: "Comedic slow zoom on Benny's blank expression.",
        characters: ["char-noob", "char-ninja"],
        dialogue: [
          {
            id: "d-4-4",
            characterId: "char-noob",
            emotion: "CONFUSED",
            text: "Huh... they must have moved the door in the new update :D",
            duration: 3.5,
          },
          {
            id: "d-4-5",
            characterId: "char-ninja",
            emotion: "ANGRY",
            text: "BENNYYYYYYY!",
            duration: 2.0,
          },
        ],
      },
    ],
  },
  {
    id: "script-5",
    ideaId: "idea-9",
    title: "Wrong Player",
    description: "Display name swap prank tricks the entire lobby into chasing the wrong suspect.",
    status: "DRAFT",
    hook: "One letter made all the difference...",
    tags: ["Prank", "Twins", "MM2", "DisplayNames"],
    estimatedDuration: 30,
    createdAt: "2026-09-24T15:00:00.000Z",
    updatedAt: "2026-09-28T11:00:00.000Z",
    characters: ["char-sheriff", "char-troll", "char-detective"],
    scenes: [
      {
        id: "scene-5-1",
        title: "The Interrogation Room",
        description: "Sheriff Knox corners Gizmo while Inspector Blox examines the leaderboard.",
        duration: 16,
        notes: "Harsh spotlight shining on the interrogation table.",
        characters: ["char-sheriff", "char-troll", "char-detective"],
        dialogue: [
          {
            id: "d-5-1",
            characterId: "char-sheriff",
            emotion: "ANGRY",
            text: "We got you, Gizmo! The kill feed clearly says G-I-Z-M-O!",
            duration: 3.5,
          },
          {
            id: "d-5-2",
            characterId: "char-troll",
            emotion: "HAPPY",
            text: "Look closer at my name tag, officer Knox...",
            duration: 3.0,
          },
          {
            id: "d-5-3",
            characterId: "char-detective",
            emotion: "SURPRISED",
            text: "Hold on Knox! That's a capital 'I' instead of an 'l'! He's innocent!",
            duration: 4.0,
          },
        ],
      },
      {
        id: "scene-5-2",
        title: "The Real Culprit Escapes",
        description: "Behind the one-way glass, the actual culprit waves goodbye and takes the vent.",
        duration: 14,
        notes: "Vent squeak sound effect and laughing emote.",
        characters: ["char-sheriff", "char-troll"],
        dialogue: [
          {
            id: "d-5-4",
            characterId: "char-troll",
            emotion: "EXCITED",
            text: "You just got display name bamboozled!",
            duration: 2.5,
          },
          {
            id: "d-5-5",
            characterId: "char-sheriff",
            emotion: "CONFUSED",
            text: "I am never trusting font kerning again...",
            duration: 3.0,
          },
        ],
      },
    ],
  },
];
