import { IdeaItem } from "./types";

export const INITIAL_IDEAS: IdeaItem[] = [
  {
    id: "idea-1",
    title: "He Had ONE Job",
    description:
      "Sheriff has a clear point-blank line of sight on the murderer who was trapped behind boxes, but shoots an innocent bacon hair instead, throwing the entire round into chaos.",
    category: "MM2",
    status: "IDEA",
    priority: "HOT",
    tags: ["MM2", "SheriffFail", "FunnyMoments", "Clutch"],
    potentialScore: 9.5,
    createdAt: "2026-09-20T10:15:00.000Z",
    updatedAt: "2026-09-28T14:30:00.000Z",
  },
  {
    id: "idea-2",
    title: "The Sheriff Trusted The Wrong Player",
    description:
      "The innocent player acts as a trusted bodyguard guiding the sheriff through the mansion, only for the actual killer to disguise as their twin avatar and strike at the final second.",
    category: "MM2",
    status: "PLANNING",
    priority: "HOT",
    tags: ["MM2", "Betrayal", "PlotTwist", "RobloxStory"],
    potentialScore: 9.8,
    createdAt: "2026-09-21T09:00:00.000Z",
    updatedAt: "2026-09-27T16:45:00.000Z",
  },
  {
    id: "idea-3",
    title: "Never Follow The Noob",
    description:
      "A comedy skit following a default avatar player who claims to know a secret backdoor glitch in Natural Disaster Survival, leading 10 players into an erupting volcano.",
    category: "FUNNY",
    status: "SCRIPTING",
    priority: "HIGH",
    tags: ["RobloxMeme", "Noob", "ComedySkit", "NaturalDisaster"],
    potentialScore: 8.7,
    createdAt: "2026-09-22T11:20:00.000Z",
    updatedAt: "2026-09-28T08:15:00.000Z",
  },
  {
    id: "idea-4",
    title: "The Murderer Was AFK",
    description:
      "Everyone in the lobby assumes the murderer went AFK in the spawn garage and gathers around to emote, until the murderer suddenly snaps back and wipes the lobby in 5 seconds.",
    category: "MM2",
    status: "PRODUCTION",
    priority: "MEDIUM",
    tags: ["MM2", "AFKTrap", "Jumpscare", "Trolling"],
    potentialScore: 8.2,
    createdAt: "2026-09-18T14:00:00.000Z",
    updatedAt: "2026-09-26T12:00:00.000Z",
  },
  {
    id: "idea-5",
    title: "Don't Open That Door",
    description:
      "Cinematic suspense roleplay where players locked inside an abandoned research lab hear scratching behind door 14. High suspense sound design and atmospheric lighting.",
    category: "STORY",
    status: "PLANNING",
    priority: "HIGH",
    tags: ["RobloxHorror", "Cinematic", "Storyline", "Doors"],
    potentialScore: 9.1,
    createdAt: "2026-09-19T16:30:00.000Z",
    updatedAt: "2026-09-25T17:10:00.000Z",
  },
  {
    id: "idea-6",
    title: "The Last Player Alive",
    description:
      "Solo innocent player plays peak hide-and-seek against a sweat murderer with Chroma Luger across the Biohazard facility, clutching the gun drop with 3 seconds remaining.",
    category: "MM2",
    status: "PUBLISHED",
    priority: "HOT",
    tags: ["MM2", "ClutchGun", "SweatLobby", "ProPlay"],
    potentialScore: 9.6,
    createdAt: "2026-09-15T12:00:00.000Z",
    updatedAt: "2026-09-24T18:00:00.000Z",
  },
  {
    id: "idea-7",
    title: "When The Sheriff Has No Aim",
    description:
      "A fast-paced comedy montage featuring 12 missed shots at point blank range with cartoon hitmarkers and hilarious slow-mo sound effects.",
    category: "SHORT",
    status: "PUBLISHED",
    priority: "HOT",
    tags: ["Shorts", "MemeEdit", "SheriffAim", "RobloxShorts"],
    potentialScore: 9.4,
    createdAt: "2026-09-14T10:00:00.000Z",
    updatedAt: "2026-09-23T11:30:00.000Z",
  },
  {
    id: "idea-8",
    title: "He Pretended To Be Innocent",
    description:
      "Social experiment where I acted completely innocent, begged the sheriff for protection, and threw fake accusations until the final two players remained.",
    category: "MM2",
    status: "IDEA",
    priority: "HIGH",
    tags: ["MM2", "SocialExperiment", "MindGames", "Acting"],
    potentialScore: 8.9,
    createdAt: "2026-09-23T15:00:00.000Z",
    updatedAt: "2026-09-28T19:00:00.000Z",
  },
  {
    id: "idea-9",
    title: "Wrong Player",
    description:
      "Two friends wearing identical avatar outfits swap usernames using display name trickery, confusing the lobby into arresting the completely wrong person.",
    category: "FUNNY",
    status: "IDEA",
    priority: "MEDIUM",
    tags: ["Trolling", "TwinsPrank", "DisplayNames", "RobloxFun"],
    potentialScore: 7.8,
    createdAt: "2026-09-24T08:30:00.000Z",
    updatedAt: "2026-09-27T09:20:00.000Z",
  },
  {
    id: "idea-10",
    title: "Nobody Expected This Ending",
    description:
      "Narrative machinima where the detective reveals that the missing explorer wasn't taken by monsters, but built an underground society beneath Bloxburg.",
    category: "STORY",
    status: "SCRIPTING",
    priority: "HOT",
    tags: ["RobloxMovie", "Lore", "PlotTwist", "Machinima"],
    potentialScore: 9.7,
    createdAt: "2026-09-17T13:40:00.000Z",
    updatedAt: "2026-09-26T20:15:00.000Z",
  },
  {
    id: "idea-11",
    title: "Trading From Default Knife to Harvester in 24 Hours",
    description:
      "Documenting every trade starting with a common Combat Knife, flipping through value tiers using trade hubs until securing the Harvester ancient godly.",
    category: "TREND",
    status: "PRODUCTION",
    priority: "HOT",
    tags: ["TradingChallenge", "MM2Trading", "Harvester", "ProfitGuide"],
    potentialScore: 9.3,
    createdAt: "2026-09-16T18:00:00.000Z",
    updatedAt: "2026-09-28T15:45:00.000Z",
  },
  {
    id: "idea-12",
    title: "I Survived 100 Days in a Broken Roblox City",
    description:
      "Roleplay survival challenge surviving toxic rain, rogue player gangs, and scarce resources in a custom post-apocalyptic map.",
    category: "LONG_VIDEO",
    status: "PLANNING",
    priority: "HIGH",
    tags: ["100Days", "SurvivalChallenge", "Longform", "Apocalypse"],
    potentialScore: 9.1,
    createdAt: "2026-09-12T14:10:00.000Z",
    updatedAt: "2026-09-25T11:00:00.000Z",
  },
  {
    id: "idea-13",
    title: "Spinning Wheel Decides My MM2 Loadout",
    description:
      "A viewer-interactive wheel decides whether I can only use commons, play with inverted mouse controls, or throw knives blindly every 10 seconds.",
    category: "TREND",
    status: "IDEA",
    priority: "MEDIUM",
    tags: ["MysteryWheel", "LoadoutChallenge", "MM2Trends", "Interactive"],
    potentialScore: 7.9,
    createdAt: "2026-09-25T10:00:00.000Z",
    updatedAt: "2026-09-27T14:10:00.000Z",
  },
  {
    id: "idea-14",
    title: "The Most Toxic Lobby in Roblox History",
    description:
      "Entering a competitive lobby that trash-talks everyone, then casually breaking out pro-tier movement and silent knife throws to win 10 rounds consecutively.",
    category: "FUNNY",
    status: "PRODUCTION",
    priority: "HIGH",
    tags: ["Satisfying", "Clutch", "ToxicTrolling", "Revenge"],
    potentialScore: 8.8,
    createdAt: "2026-09-19T09:30:00.000Z",
    updatedAt: "2026-09-28T10:20:00.000Z",
  },
  {
    id: "idea-15",
    title: "Undercover as a Guest in 2026",
    description:
      "Re-creating the legendary Guest 666 avatar and testing how newer Roblox generation players react to mythical creepypasta lore in Brookhaven.",
    category: "OTHER",
    status: "PLANNING",
    priority: "LOW",
    tags: ["Guest666", "Brookhaven", "Undercover", "RobloxLore"],
    potentialScore: 6.9,
    createdAt: "2026-09-21T16:00:00.000Z",
    updatedAt: "2026-09-24T12:00:00.000Z",
  },
  {
    id: "idea-16",
    title: "Escaping The Impossible Roblox Obby",
    description:
      "Rapid-fire cuts attempting frame-perfect ladder flicks and wraparounds on difficulty tier 10 tower obby, set to high BPM electronic beat.",
    category: "SHORT",
    status: "PUBLISHED",
    priority: "HIGH",
    tags: ["Obby", "Shorts", "Hardcore", "GamingClips"],
    potentialScore: 8.6,
    createdAt: "2026-09-10T11:00:00.000Z",
    updatedAt: "2026-09-20T17:30:00.000Z",
  },
  {
    id: "idea-17",
    title: "The Secret Room Nobody Found in MM2",
    description:
      "Exploration video breaking down an out-of-bounds spectator glitched chamber in the Workplace map and the hidden creator Easter eggs tucked inside.",
    category: "MM2",
    status: "ARCHIVED",
    priority: "LOW",
    tags: ["MM2Secrets", "EasterEggs", "Glitch", "Archived"],
    potentialScore: 6.5,
    createdAt: "2026-08-15T09:00:00.000Z",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "idea-18",
    title: "Can 1 Pro Beat 50 Noobs in Roblox?",
    description:
      "Massive private server experiment putting 1 seasoned competitive player against an entire server of 50 new players in infected tag mode.",
    category: "LONG_VIDEO",
    status: "SCRIPTING",
    priority: "HOT",
    tags: ["ProVs50", "ChallengeVideo", "MrBeastStyle", "LongVideo"],
    potentialScore: 9.9,
    createdAt: "2026-09-18T10:00:00.000Z",
    updatedAt: "2026-09-27T18:00:00.000Z",
  },
];
