import { Character } from "./types";

export const INITIAL_CHARACTERS: Character[] = [
  {
    id: "char-sheriff",
    name: "Sheriff Knox",
    role: "MAIN",
    personality: "Authoritative, over-confident, jumps at shadows, quick to draw but terrible aim.",
    description:
      "The self-appointed guardian of every MM2 lobby. Wears the classic sheriff badge with pride and claims a 99% accuracy rate despite frequently shooting innocent bystanders.",
    tags: ["Sheriff", "Hero", "MM2", "Revolver"],
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    outfit: "Brown Western trenchcoat, silver star badge, cowboy hat, dual holster belt",
    notes: "Main protagonist of the channel. Voice lines should sound like a dramatic 80s cop film parody.",
    createdAt: "2026-09-01T12:00:00.000Z",
    updatedAt: "2026-09-25T14:30:00.000Z",
  },
  {
    id: "char-murderer",
    name: "Slick Blade (The Murderer)",
    role: "VILLAIN",
    personality: "Silent, theatrical, unpredictable, loves pretending to be an innocent bystander until lights go out.",
    description:
      "The lobby's biggest nightmare wielding a Chroma Fang. Specializes in social engineering: crouch-spamming alongside noobs before striking when their back is turned.",
    tags: ["Murderer", "Villain", "MM2", "GodlyKnife"],
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    outfit: "Midnight black hoodie with glowing purple trim, hockey mask, silver combat boots",
    notes: "Always gets the suspenseful bass drop cue before revealing the knife.",
    createdAt: "2026-09-02T10:00:00.000Z",
    updatedAt: "2026-09-24T18:15:00.000Z",
  },
  {
    id: "char-noob",
    name: "Bacon Benny (The Noob)",
    role: "SUPPORTING",
    personality: "Clueless, delightfully wholesome, accidentally survives cataclysms through sheer ignorance.",
    description:
      "Classic default bacon hair avatar who wanders into crossfires, pushes wrong buttons in elevator games, and unknowingly picks up dropped sheriff guns.",
    tags: ["Noob", "BaconHair", "Comedy", "Meme"],
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80",
    outfit: "Original 2014 Bacon hair, blue motorcycle jacket, green cargo trousers, big goofy grin",
    notes: "The audience favorite comic relief. Often speaks with broken grammar and question marks.",
    createdAt: "2026-09-03T11:20:00.000Z",
    updatedAt: "2026-09-26T16:00:00.000Z",
  },
  {
    id: "char-ninja",
    name: "Kage (The Ninja)",
    role: "MAIN",
    personality: "Disciplined, swift, deadpan sarcasm, master of wall-flicks and parkour obby shortcuts.",
    description:
      "A competitive parkour veteran who treats every Roblox map like a ninja warrior trial. Silent until someone disrespects movement mechanics.",
    tags: ["Ninja", "Pro", "Movement", "Parkour"],
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    outfit: "Dark shinobi wrap, neon cyan sash, twin katanas on back, stealth visor",
    notes: "Performs the clutch jumps and cinematic escape stunts in videos.",
    createdAt: "2026-09-04T09:00:00.000Z",
    updatedAt: "2026-09-27T12:00:00.000Z",
  },
  {
    id: "char-detective",
    name: "Inspector Blox",
    role: "SUPPORTING",
    personality: "Hyper-analytical, takes notes on spectator angles, over-explains simple clues.",
    description:
      "Analyzes kill feed timestamps and player positions with ridiculous mathematical precision. Frequently solved the mystery right as they get eliminated.",
    tags: ["Detective", "Investigator", "Story", "Smart"],
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80",
    outfit: "Grey houndstooth fedora, magnifying glass accessory, vintage suit and tie",
    notes: "Narrates dramatic inner monologues during intense investigation sequences.",
    createdAt: "2026-09-05T14:10:00.000Z",
    updatedAt: "2026-09-23T11:45:00.000Z",
  },
  {
    id: "char-lucky",
    name: "Lucky Clover",
    role: "SUPPORTING",
    personality: "Superstitious, perpetually optimistic, believes specific emote spins bring Godly loot crates.",
    description:
      "Known for opening thousands of mystery crates while wearing emerald lucky charms. Somehow survives gunshots because another player stepped in the way at the exact millisecond.",
    tags: ["Lucky", "Crates", "Gambler", "Funny"],
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80",
    outfit: "Emerald clover top hat, green varsity jacket, golden sneakers",
    notes: "Used in crate unboxing skits and miraculous survival scenes.",
    createdAt: "2026-09-06T15:30:00.000Z",
    updatedAt: "2026-09-22T10:00:00.000Z",
  },
  {
    id: "char-shadow",
    name: "Shadow Void",
    role: "VILLAIN",
    personality: "Cold, calculating, manipulative syndicate boss of black market trading rings.",
    description:
      "The mastermind pulling strings behind rogue trade lobbies. Never shows their true inventory and uses proxies to bait novice traders into unfair ancient knife deals.",
    tags: ["Shadow", "Mastermind", "Villain", "Trading"],
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80",
    outfit: "Obsidian crown, purple smoke aura, velvet high-collar cape, corrupted scythe",
    notes: "Antagonist in multi-part story machinimas and high-stakes trading series.",
    createdAt: "2026-09-07T16:00:00.000Z",
    updatedAt: "2026-09-28T09:15:00.000Z",
  },
  {
    id: "char-trader",
    name: "Ritchie 'The Trader'",
    role: "NPC",
    personality: "Hustler, fast-talking, obsessed with value charts and rap spreadsheets.",
    description:
      "Stands near the spawn lobby tree 24/7 trading common pets and vintage weapons. Will offer 17 unwanted items for your rare collectible.",
    tags: ["Trader", "NPC", "Values", "Hustler"],
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80",
    outfit: "Gold chain necklace, neon sunglasses, tailored pinstripe suit, briefcase accessory",
    notes: "Provides quests, trade offers, and market comedy lines.",
    createdAt: "2026-09-08T08:45:00.000Z",
    updatedAt: "2026-09-25T13:20:00.000Z",
  },
  {
    id: "char-troll",
    name: "Gizmo (The Troll)",
    role: "SPECIAL_GUEST",
    personality: "Mischievous, giggly, soundboard enthusiast, master of invisible trap blocks.",
    description:
      "Builds fake ladders, blocks elevator doors with balloon physics, and plays funny goat sounds over voice chat at the climax of scary scenes.",
    tags: ["Troll", "Prankster", "SpecialGuest", "Soundboard"],
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80",
    outfit: "Neon rainbow propeller beanie, mismatched clown socks, megaphone accessory",
    notes: "Guest recurring role in funny collaboration videos.",
    createdAt: "2026-09-09T13:00:00.000Z",
    updatedAt: "2026-09-27T17:40:00.000Z",
  },
  {
    id: "char-mysterious",
    name: "The Glitch (Mysterious Player)",
    role: "SPECIAL_GUEST",
    personality: "Silent, eerie, teleports when unobserved, leaves cryptic numerical binary chats.",
    description:
      "A legend whispered in server discords. Appears at the edge of the render distance during nighttime maps before vanishing without a trace.",
    tags: ["Myth", "Glitch", "Creepypasta", "Horror"],
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
    outfit: "Static noise patterned skin, missing texture silhouette, glitching halo",
    notes: "Appears during ARG story arcs and Halloween specials.",
    createdAt: "2026-09-10T18:30:00.000Z",
    updatedAt: "2026-09-26T21:00:00.000Z",
  },
];
